// These are programs owned by Ary. Caller data is passed in argv and never interpolated.
export const macScripts = {
  media: `function run(a) { var p = Application(a[0]); if (!p.running()) throw Error('Player must already be running'); switch(a[1]) { case 'play': p.play(); break; case 'pause': p.pause(); break; case 'next': p.nextTrack(); break; case 'previous': p.previousTrack(); break; default: throw Error('Invalid media action'); } return 'Media command accepted'; }`,
  volume: `function run(a) { var s=Application.currentApplication(); s.includeStandardAdditions=true; s.setVolume(null,{outputVolume:Number(a[0])}); return JSON.stringify(s.getVolumeSettings()); }`,
  clipboard_read: `ObjC.import('AppKit'); function run() { var p=$.NSPasteboard.generalPasteboard; var v=p.stringForType($.NSPasteboardTypeString); return ObjC.unwrap(v) || '';  }`,
  clipboard_write: `ObjC.import('AppKit'); function run(a) { var p=$.NSPasteboard.generalPasteboard; p.clearContents; if (!p.setStringForType($(a[0]),$.NSPasteboardTypeString)) throw Error('Clipboard write failed'); return 'Clipboard updated'; }`,
  hide_others: `function run(a) { var target=Application(a[0]); if (!target.running()) throw Error('App must already be running'); target.activate(); var s=Application('com.apple.systemevents'); var found=false; s.applicationProcesses().forEach(function(p){ if(p.bundleIdentifier()===a[1]) found=true; }); if(!found) throw Error('App is not a visible process'); s.applicationProcesses().forEach(function(p){ if(!p.backgroundOnly() && p.bundleIdentifier()!==a[1]) p.visible=false; }); return 'Other apps hidden'; }`,
  quit_app: `function run(a) { var p=Application(a[0]); if(!p.running()) return 'App was already stopped'; p.quit(); delay(0.25); if(p.running()) throw Error('App remains open: review its save or quit dialog'); return 'App quit gracefully'; }`,
  lock_screen: `function run() { var s=Application('com.apple.systemevents'); s.keystroke('q',{using:['control down','command down']}); return 'Lock shortcut dispatched; screen state not independently verified'; }`,
  create_note: `function run(a) { var n=Application('com.apple.Notes'); var f=n.defaultAccount.defaultFolder(); function esc(v){return v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;');} var note=n.Note({name:a[0],body:'<h1>'+esc(a[0])+'</h1><div>'+esc(a[1]).replace(/\\n/g,'<br>')+'</div>'}); f.notes.push(note); return note.id(); }`,
  create_reminder: `function run(a) { var r=Application('com.apple.reminders'); var props={name:a[0],body:a[1]}; if(a[2]) props.dueDate=new Date(a[2]); var item=r.Reminder(props); r.defaultList.reminders.push(item); return item.id(); }`,
} as const;
